FROM ubuntu:focal
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y git cmake build-essential ninja-build
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y curl zip unzip tar
